export default {
  BasicScene: require('./BasicScene').default,
  BasicTextureScene: require('./BasicTextureScene').default,
  MultiBasicScene: require('./MultiBasicScene').default,
  // REGLTextureScene: require('./REGLTextureScene').default,
  REGLBunnyScene: require('./REGLBunnyScene').default,
  REGLLightingScene: require('./REGLLightingScene').default,
  REGLParticlesScene: require('./REGLParticlesScene').default,
  THREEBasicScene: require('./THREEBasicScene').default,
  THREETextureScene: require('./THREETextureScene').default,
  THREEOBJScene: require('./THREEOBJScene').default,
  THREEPerfScene: require('./THREEPerfScene').default,
  THREEBasicTouchScene: require('./THREEBasicTouchScene').default,
  Conformance: require('./Conformance').default,
};
